apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: springboot-multisource1
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  sources:
    # Source 1: values repo
    - repoURL: https://github.com/devops4solutions/eks-hello-svc.git
      targetRevision: argocd
      ref: values
    # Source 2: Helm chart in Git repo
    - repoURL: https://devops4solutions.github.io/springboot-helm-chart/
      chart: springboot
      targetRevision: 0.1.5
      helm:
        valueFiles:
          - $values/terraform/dev/values_argocd.yaml
