apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: springboot-dev
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  sources:
  - repoURL: https://github.com/Ramlu/deploy-argocd-app.git
    targetRevision: main
    ref: values
    # Source 2: Helm chart in Git repo
  - repoURL: https://Ramlu.github.io/springboot-helm-chart/
    chart: springboot
    targetRevision: 0.1.5
    helm:
        valueFiles:
          - $values/deploy/dev/values.yaml
    # PostSync Hook
  - repoURL: https://github.com/Ramlu/deploy-argocd-app.git
    targetRevision: main
    path: deploy/dev/post-sync
