apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  # add an additional local user with apiKey and login capabilities
  #   apiKey - allows generating API keys
  #   login - allows to login using UI
  accounts.developer: apiKey, login
  accounts.devops: apiKey, login
  accounts.tester: apiKey, login

  # disables user. User is enabled by default
  #ßadmin.enabled: "false"